version: '3.9'

services:
  app:
    container_name: app
    image: golang:1.21
    volumes:
      - .:/go/src
    ports:
      - 8080:8080
    command: tail -f "/dev/null"

  app-mongo:
    container_name: app-mongo
    image: mongo:7.0.0
    volumes:
      - .database:/data/db
    ports:
      - 27017:27017

